---
abstract: 'light weight Catalyst-ish web application framework'
author:
  - 'Daisuke Murase <typester@cpan.org>'
build_requires:
  HTTP::Cookies: 0
  Test::More: 0.98
  Test::Output: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ark
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Ark:
    file: lib/Ark.pm
    version: 0.391
  Ark::Action:
    file: lib/Ark/Action.pm
    version: 0
  Ark::ActionClass::Form:
    file: lib/Ark/ActionClass/Form.pm
    version: 0
  Ark::Component:
    file: lib/Ark/Component.pm
    version: 0
  Ark::Context:
    file: lib/Ark/Context.pm
    version: 0
  Ark::Context::Debug:
    file: lib/Ark/Context/Debug.pm
    version: 0
  Ark::Controller:
    file: lib/Ark/Controller.pm
    version: 0
  Ark::Controller::Form:
    file: lib/Ark/Controller/Form.pm
    version: 0
  Ark::Core:
    file: lib/Ark/Core.pm
    version: 0
  Ark::Form:
    file: lib/Ark/Form.pm
    version: 0
  Ark::Logger:
    file: lib/Ark/Logger.pm
    version: 0
  Ark::Model:
    file: lib/Ark/Model.pm
    version: 0
  Ark::Model::Adaptor:
    file: lib/Ark/Model/Adaptor.pm
    version: 0
  Ark::Models:
    file: lib/Ark/Models.pm
    version: 0
  Ark::Plugin:
    file: lib/Ark/Plugin.pm
    version: 0
  Ark::Plugin::Authentication:
    file: lib/Ark/Plugin/Authentication.pm
    version: 0
  Ark::Plugin::Authentication::Backend:
    file: lib/Ark/Plugin/Authentication/Backend.pm
    version: 0
  Ark::Plugin::Authentication::Credential::OpenID:
    file: lib/Ark/Plugin/Authentication/Credential/OpenID.pm
    version: 0
  Ark::Plugin::Authentication::Credential::Password:
    file: lib/Ark/Plugin/Authentication/Credential/Password.pm
    version: 0
  Ark::Plugin::Authentication::Credential::Twitter:
    file: lib/Ark/Plugin/Authentication/Credential/Twitter.pm
    version: 0
  Ark::Plugin::Authentication::Store::DBIx::Class:
    file: lib/Ark/Plugin/Authentication/Store/DBIx/Class.pm
    version: 0
  Ark::Plugin::Authentication::Store::Minimal:
    file: lib/Ark/Plugin/Authentication/Store/Minimal.pm
    version: 0
  Ark::Plugin::Authentication::Store::Model:
    file: lib/Ark/Plugin/Authentication/Store/Model.pm
    version: 0
  Ark::Plugin::Authentication::Store::Null:
    file: lib/Ark/Plugin/Authentication/Store/Null.pm
    version: 0
  Ark::Plugin::Authentication::User:
    file: lib/Ark/Plugin/Authentication/User.pm
    version: 0
  Ark::Plugin::CSRFDefender:
    file: lib/Ark/Plugin/CSRFDefender.pm
    version: 0
  Ark::Plugin::Encoding::MobileJP:
    file: lib/Ark/Plugin/Encoding/MobileJP.pm
    version: 0
  Ark::Plugin::Encoding::Null:
    file: lib/Ark/Plugin/Encoding/Null.pm
    version: 0
  Ark::Plugin::Encoding::Unicode:
    file: lib/Ark/Plugin/Encoding/Unicode.pm
    version: 0
  Ark::Plugin::FormValidator::Lite:
    file: lib/Ark/Plugin/FormValidator/Lite.pm
    version: 0
  Ark::Plugin::I18N:
    file: lib/Ark/Plugin/I18N.pm
    version: 0
  Ark::Plugin::MobileAgent:
    file: lib/Ark/Plugin/MobileAgent.pm
    version: 0
  Ark::Plugin::ReproxyCallback:
    file: lib/Ark/Plugin/ReproxyCallback.pm
    version: 0
  Ark::Plugin::ReproxyCallback::OpenSocial:
    file: lib/Ark/Plugin/ReproxyCallback/OpenSocial.pm
    version: 0
  Ark::Plugin::Session:
    file: lib/Ark/Plugin/Session.pm
    version: 0
  Ark::Plugin::Session::Backend:
    file: lib/Ark/Plugin/Session/Backend.pm
    version: 0
  Ark::Plugin::Session::State::Cookie:
    file: lib/Ark/Plugin/Session/State/Cookie.pm
    version: 0
  Ark::Plugin::Session::State::OpenSocial:
    file: lib/Ark/Plugin/Session/State/OpenSocial.pm
    version: 0
  Ark::Plugin::Session::State::URI:
    file: lib/Ark/Plugin/Session/State/URI.pm
    version: 0
  Ark::Plugin::Session::State::URI::ExtendContext:
    file: lib/Ark/Plugin/Session/State/URI/ExtendContext.pm
    version: 0
  Ark::Plugin::Session::Store::Memory:
    file: lib/Ark/Plugin/Session/Store/Memory.pm
    version: 0
  Ark::Plugin::Session::Store::Model:
    file: lib/Ark/Plugin/Session/Store/Model.pm
    version: 0
  Ark::Request:
    file: lib/Ark/Request.pm
    version: 0
  Ark::Response:
    file: lib/Ark/Response.pm
    version: 0
  Ark::Test:
    file: lib/Ark/Test.pm
    version: 0
  Ark::Test::Context:
    file: lib/Ark/Test/Context.pm
    version: 0
  Ark::View:
    file: lib/Ark/View.pm
    version: 0
  Ark::View::JSON:
    file: lib/Ark/View/JSON.pm
    version: 0
  Ark::View::MT:
    file: lib/Ark/View/MT.pm
    version: 0
  Ark::View::TT:
    file: lib/Ark/View/TT.pm
    version: 0
  Ark::View::Xslate:
    file: lib/Ark/View/Xslate.pm
    version: 0
recommends:
  DBD::SQLite: 0
  DBIx::Class: 0
  Encode::JP::Mobile: 0
  HTTP::MobileAgent: 0
  HTTP::MobileAgent::Plugin::Charset: 0
  LWPx::ParanoidAgent: 0
  Locale::Maketext::Lexicon: 0
  Locale::Maketext::Simple: 0
  Net::OpenID::Consumer: 0
  OAuth::Lite: 0
  Text::MicroTemplate::Extended: 0.09
requires:
  CGI::Simple: 0
  Class::Data::Inheritable: 0
  Clone: 0
  Data::UUID: 0
  Data::Util: 0
  Devel::StackTrace: 0
  Digest::SHA1: 0
  Exporter::AutoClean: 0
  HTML::Entities: 0
  HTML::Shakan: 0.16
  Module::Pluggable::Object: 0
  Mouse: 1.0
  Object::Container: 0.08
  Path::AttrRouter: 0.03
  Path::Class: 0.16
  Plack: 0
  Plack::Request: 0
  Text::MicroTemplate: 0
  Text::SimpleTable: 0
  Try::Tiny: 0.02
  URI: 0
  URI::WithBase: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/ark-framework/ark-perl/issues
  homepage: https://github.com/ark-framework/ark-perl
  repository: git://github.com/ark-framework/ark-perl.git
version: 0.391
x_contributors:
  - 'Masakazu Ohtsuka <o.masakazu@gmail.com>'
  - 'mattn <mattn.jp@gmail.com>'
  - 'Ryo Miyake <ryo.studiom@gmail.com>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Shinichiro Sei <sei@kayac.com>'
  - 'hisaichi5518 <info@moe-project.com>'
  - 'ichirin2501 <ichirin.2501@gmail.com>'
  - 'Daisuke Murase <typester@gmail.com>'
  - 'FUJIWARA Shunichiro <fujiwara.shunichiro@gmail.com>'
  - 'Masatoshi Kawazoe (acidlemon) <kawazoe-masatoshi@kayac.com>'
  - 'tei-you <tei-you@kayac.com>'
  - 'Songmu <y.songmu@gmail.com>'
